### PR TITLE
Prevent NotificationAlert from appearing

### LINKED ISSUE #680: Notifications Opt-In Modal Appearing Incorrectly and Repeatedly
**Describe the bug**
The notifications opt-in modal is appearing repeatedly for users that have already opted in to notifications as well as for users that are not signed-in to near.org. This is causing a very frustrating user experience on the gateway.

**To Reproduce**
1. Go to near.org
2. Opt-in to notificatins
3. See modal again after opting in

**Expected behavior**
After a user opts-in to notifications they should not be shown any opt-in modal. 

**Screenshots**
Slack th

**Desktop (please complete the following information):**
- MacOS 14 + Brave Browser

**Additional context**
This has been reported by multiple different users. Slack thread here for additional context --> https://pagodaplatform.slack.com/archives/C050U2B25RB/p1696795713296339

cc @shelegdmitriy @charleslavon

### PR DESCRIPTION
**Pull request by shelegdmitriy**
Closes #680

### CODE REVIEW

File: src/pages/index.tsx [hunk 1]
```diff
@@ -80,21 +81,21 @@ const HomePage: NextPageWithLayout = () => {
...
-        cacheTosData.agreementsForUser[cacheTosData.agreementsForUser.length - 1].value ===
-        cacheTosData.latestTosVersion;
+        cacheTocData.agreementsForUser[cacheTocData.agreementsForUser.length - 1].value ===
+        cacheTocData.latestTosVersion;
       // check if user has already turned on notifications
-      const { showOnTS } = getNotificationLocalStorage() || {};
+      const showNotificationPrompt = showNotificationModal();
 
-      if (!iosHomeScreenPrompt && ((tosAccepted && !showOnTS) || (tosAccepted && showOnTS < Date.now()))) {
+      if (!subscribeError && showNotificationPrompt && tosAccepted && (!showOnTS || !iosHomeScreenPrompt)) {
```
Comment (shelegdmitriy) [inline src/pages/index.tsx:92]: If there is an error we won't show NotificationAlert no more

File: src/utils/notifications.ts [hunk 2]
```diff
@@ -51,9 +51,23 @@ export const detectIOSVersion = () => {
...
 
-const registerServiceWorker = () => navigator.serviceWorker.register('/service-worker.js');
+const registerServiceWorker = () => {
+  try {
+    return navigator.serviceWorker.register('/service-worker.js');
+  }
+  catch (error) {
+    console.error('Error while registering service-worker.', error);
+  }
+};
```
Comment (shelegdmitriy) [inline src/utils/notifications.ts:70]: This will help us understand which part has failed

File: src/utils/notificationsLocalStorage.ts [hunk 3]
```diff
@@ -92,6 +94,13 @@ export const setProcessError = (error: any) => {
       subscribeError: errorMessage,
     }),
   );
+  openToast({
+    id: 'notifications-subscription-error',
+    type: 'ERROR',
+    title: "Push notification error",
+    description: `${errorMessage}. Please try again later or send us a message if the problem persists.`,
+    duration: 5000,
+  });
```
Comment (shelegdmitriy) [inline src/utils/notificationsLocalStorage.ts:103]: It's worth to show users that there is something went wrong. At least we'll have a better understanding what should we improve.

I wonder if we should add an analytics event here?

**Comment by calebjacob** [comment]
Unfortunately, I ended up having to refactor parts of this logic to fix a bug - so we're going to end up with a pretty ugly merge conflict. Let's wait until this is approved and merged first: https://github.com/near/near-discovery/pull/686

Sorry for the bad timing @shelegdmitriy

**Comment by shelegdmitriy** [comment]
> Unfortunately, I ended up having to refactor parts of this logic to fix a bug - so we're going to end up with a pretty ugly merge conflict. Let's wait until this is approved and merged first: https://github.com/near/near-discovery/pull/686
> 
> 
> 
> Sorry for the bad timing @shelegdmitriy 

Sure thing! I'll mark this one as draft then

File: src/utils/notificationsLocalStorage.ts (hunk 3 above)
Comment (calebjacob) [reply src/utils/notificationsLocalStorage.ts]: Good question - I'll defer to @charleslavon on this one. Seems like a good idea to track it.

File: src/components/NotificationsAlert.tsx [hunk 4]
```diff
@@ -12,20 +12,21 @@ import {
 } from '@/utils/notifications';
 import { isNotificationSupported, isPermisionGranted, isPushManagerSupported } from '@/utils/notificationsHelpers';
 import { getNotificationLocalStorage, setNotificationsSessionStorage } from '@/utils/notificationsLocalStorage';
-import type { TosData } from '@/utils/types';
+import type { TocData } from '@/utils/types';
```
Comment (calebjacob) [inline src/components/NotificationsAlert.tsx:15]: What does `Toc` stand for? I know `Tos => Terms of Service`. Just curious about the renaming.

**Review by calebjacob — APPROVED** [review]
Overall looks good to me. Let's see what Charles thinks about tracking the failure event.

File: src/components/NotificationsAlert.tsx (hunk 4 above)
Comment (shelegdmitriy) [reply src/components/NotificationsAlert.tsx:15]: I was thinking about `Terms of Conditions => Toc`. But let's keep `Tos` then.

File: src/utils/notificationsLocalStorage.ts (hunk 3 above)
Comment (charleslavon) [reply src/utils/notificationsLocalStorage.ts]: this error message is helpful 👍🏾 .  We don't need the analytics events, because we have this info via the serverless fn logs

**Review by charleslavon — APPROVED** [review]
