### PR TITLE
fix: adjust styles for form to scroll on select other on motivation page

### LINKED ISSUE #1258: Developer Survey issues
1. The 'Next' button becomes hidden and there is no way to vertically scroll down.  https://www.loom.com/share/ebf6cac41b17444999977aa950ecedfd
2. Trigger hiding the 'Gleap' support affordance on display of the developer survey, and show it upon closing/submitting the developer survey.
3. If you haven't already, get feedback from Jo & Spencer on whether they suggest any changes to the structure of the event payload to better facilitate the types of queries we'll likely want to make.
4. Rather than add a unique attribute for each question on a wizard screen `question, question2, etc` , consider storing the questions of form pages with multiple questions into an array. That way we one can iterate through the array of questions `questions[0], questions[1]` etc.  instead of needing to know how many questions to expect in each form 
Screen Shot 2024-07-19 at 9 15 20 AM

### PR DESCRIPTION
**Pull request by jackson-harris-iii**
PR address issues in the developer survery:

- ensuring the next button is visible/scrollable when the other input box is displayed 
- flatten ruddstack messages
- enable submit button on 'no thanks' selection

Closes #1258

### CODE REVIEW

**Review by charleslavon — APPROVED** [review]
👍🏾 👍🏾

File: src/components/research-form-wizard/FormPages/Motivation.tsx [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import { useResearchWizardStore } from '@/stores/researchWizard';
-import { useEffect, useState } from 'react';
+import { use, useEffect, useRef, useState } from 'react';
```
Comment (shelegdmitriy) [inline src/components/research-form-wizard/FormPages/Motivation.tsx:2]: Seems like we don't need `use here`:

```suggestion
import { useEffect, useRef, useState } from 'react';
```

**Review by shelegdmitriy — CHANGES_REQUESTED** [review]

**Comment by jackson-harris-iii** [comment]
Made an update to this address the rudderstack nested object issue discussed [here](https://github.com/near/near-discovery/issues/1258#issuecomment-2245937717)

**Comment by shelegdmitriy** [comment]
Hey @jackson-harris-iii take a look at this [video](https://www.loom.com/share/6d935552af6d487384f0fc6437e325a0?sid=f470a953-a411-4d98-9c3f-70df0a701022) please because I'm not sure about the last step on form when I select **"No thanks"** and I can't submit the form

**Comment by jackson-harris-iii** [comment]
> Hey @jackson-harris-iii take a look at this [video](https://www.loom.com/share/6d935552af6d487384f0fc6437e325a0?sid=f470a953-a411-4d98-9c3f-70df0a701022) please because I'm not sure about the last step on form when I select **"No thanks"** and I can't submit the form

Good catch, a fix has been put in [commit](https://github.com/near/near-discovery/pull/1260/commits/4e6f6d2c7c5106283bc325e70f274380dadfa88f)

**Review by shelegdmitriy — APPROVED** [review]
LGTM!
